In [1]:
import pandas as pd

In [3]:
data=pd.DataFrame({"text":["people watch youtube","youtube watch youtube","people write comment","youtube write comment"],"output":[1,1,0,0]})
data

text  output
0   people watch youtube       1
1  youtube watch youtube       1
2   people write comment       0
3  youtube write comment       0

In [4]:
#Document matrix
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
#Bag of words
BOW=CountVectorizer()

In [6]:
document_matrix=BOW.fit_transform(data["text"])

In [7]:
document_matrix

<4x5 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [8]:
#vocabularies
BOW.vocabulary_
#it list out the vocabularies based on the alphabetical order

{'people': 1, 'watch': 2, 'youtube': 4, 'write': 3, 'comment': 0}

In [9]:
#vectors
document_matrix[0].toarray()

array([[0, 1, 1, 0, 1]])

In [10]:
document_matrix[1].toarray()

array([[0, 0, 1, 0, 2]])

In [11]:
document_matrix[2].toarray()

array([[1, 1, 0, 1, 0]])

In [12]:
document_matrix[3].toarray()

array([[1, 0, 0, 1, 1]])

In [13]:
#N gram
bigram=CountVectorizer(ngram_range=(2,2))
bigramvocab=bigram.fit_transform(data["text"])


In [14]:
bigram

CountVectorizer(ngram_range=(2, 2))

In [15]:
bigramvocab

<4x6 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [16]:
bigram.vocabulary_

{'people watch': 0,
 'watch youtube': 2,
 'youtube watch': 4,
 'people write': 1,
 'write comment': 3,
 'youtube write': 5}

In [17]:
#Tri gram
trigram=CountVectorizer(ngram_range=(3,3))
trigramdata=trigram.fit_transform(data["text"])

In [18]:
trigram.vocabulary_

{'people watch youtube': 0,
 'youtube watch youtube': 2,
 'people write comment': 1,
 'youtube write comment': 3}

In [19]:
# Mixed n gram
mix=CountVectorizer(ngram_range=(1,2))
mix_vocab=mix.fit_transform(data["text"])

In [20]:
mix.vocabulary_

{'people': 1,
 'watch': 4,
 'youtube': 8,
 'people watch': 2,
 'watch youtube': 5,
 'youtube watch': 9,
 'write': 6,
 'comment': 0,
 'people write': 3,
 'write comment': 7,
 'youtube write': 10}

In [21]:
#TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()

In [22]:
tfidf.fit_transform(data["text"]).toarray()

array([[0.        , 0.61366674, 0.61366674, 0.        , 0.49681612],
       [0.        , 0.        , 0.52546357, 0.        , 0.8508161 ],
       [0.57735027, 0.57735027, 0.        , 0.57735027, 0.        ],
       [0.61366674, 0.        , 0.        , 0.61366674, 0.49681612]])

In [23]:
tfidf.get_feature_names_out()

array(['comment', 'people', 'watch', 'write', 'youtube'], dtype=object)

In [24]:
tfidf.idf_

array([1.51082562, 1.51082562, 1.51082562, 1.51082562, 1.22314355])